apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: user_database
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: observability
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-tutorial
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-tutorial
  template:
    metadata:
      labels:
        app: api-tutorial
    spec:
      containers:
        - name: app
          image: rajdeepsingh642/java-app:v1  # replace with your image
          ports:
            - containerPort: 8082
          env:
            - name: OTEL_SERVICE_NAME
              value: api-tutorial
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://tempo.observability.svc:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql.observability.svc:3306/user_database?allowPublicKeyRetrieval=true&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: api-tutorial
  namespace: observability
spec:
  selector:
    app: api-tutorial
  ports:
    - port: 8082
      targetPort: 8082
  type: NodePort
